[theme]
# App theme customization
base = "light"               # Theme base: "light"
primaryColor = "#4B89FF"     # A nice primary accent color (you can customize it)
backgroundColor = "#FFFFFF"  # White background
secondaryBackgroundColor = "#F0F2F6" # Light gray for the sidebar or secondary background
textColor = "#000000"        # Black text color
font = "sans serif"          # Font: "sans serif", "serif", or "monospace"
